### ISSUE TITLE
How is the remote-pull feature supposed to work with multiple repos?

### ISSUE THREAD

**Issue by dr460nf1r3** [arcan1s/ahriman#103]
## Describe your question below

I'm currently investigating the use of Ahriman in the Chaotic-AUR environment. A core requirement is fetching from sources other than AUR, which is supplied by the `remote-pull` command. 

The documentation states 
> target - list of remote pull triggers to be used, space separated list of strings 

So I have the following config added to test things:
~~~
[remote-pull]
target = proton-ge-custom-bin chaotic-mirrorlist

[proton-ge-custom-bin]
pull_url = https://github.com/chaotic-aur/pkgbuild-proton-ge-custom-bin
pull_branch = master

[chaotic-mirrorlist]
pull_url = https://github.com/chaotic-aur/pkgbuild-chaotic-mirrorlist.git
pull_branch = main
~~~

After triggering an update via the web UI, one of them shows up, the other doesn't. Following the repos content:
~~~
{"header":[[0,"package base","version","packages","last update","status(any status)success"]],"data":[{"0":0,"package base":"ananicy-rules-git","version":"2.2.1.r320.g62771a8-1","packages":"ananicy-rules-git","last update":"2023-08-06T12:47:15.000Z","status(any status)success":"success"},{"0":0,"package base":"ananicy","version":"2.2.1-1","packages":"ananicy","last update":"2023-08-06T12:40:11.000Z","status(any status)success":"success"},{"0":0,"package base":"proton-ge-custom-bin","version":"1:GE_Proton8_10-1","packages":"proton-ge-custom-bin","last update":"2023-08-06T13:12:41.000Z","status(any status)success":"success"}]}
~~~
This shows up when updating: 
![image](https://github.com/arcan1s/ahriman/assets/12834713/0a4f6db9-d550-494e-9889-38a641e85e2e)

Docker logs:
~~~
[INFO 2023-08-06 13:36:57,490] [ahriman.core.build_tools.sources.Sources]: update HEAD to remote at /var/lib/ahriman/ahriman/cache/tmp9rrd7ea2 using branch master
[DEBUG 2023-08-06 13:36:57,798] [ahriman.core.build_tools.sources.Sources]: fatal: couldn't find remote ref master
[ERROR 2023-08-06 13:36:57,801] [ahriman.core.repository.repository.Repository]: could not process package at /var/lib/ahriman/ahriman/cache/tmp9rrd7ea2
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/ahriman/core/repository/update_handler.py", line 110, in updates_local
Sources.fetch(cache_dir, remote=None)
File "/usr/lib/python3.11/site-packages/ahriman/core/build_tools/sources.py", line 83, in fetch
Sources._check_output("git", "fetch", "origin", branch, cwd=sources_dir, logger=instance.logger)
File "/usr/lib/python3.11/site-packages/ahriman/core/util.py", line 142, in check_output
raise subprocess.CalledProcessError(status_code, process.args)
subprocess.CalledProcessError: Command '('git', 'fetch', 'origin', 'master')' returned non-zero exit status 128.
[DEBUG 2023-08-06 13:36:57,804] [ahriman.core.build_tools.sources.Sources]: origin
~~~
Full logs of the container startup are here: [logs](https://bin.garudalinux.org/?b5acdf787b135fa8#EjLuDoZJNdirjYjroUtj8h2uVjWPhvdRVz1svNT74Zsq)
To me, it seems like it tries the clone the non-existing `master` branch instead `pull_branch = main`? So the question here is, am I doing something wrong or is this an actual bug?

Another question I have concerning this command: are separate repos required for multiple PKGBUILDs, or is it possible to drop multiple PKGBUILD folders into a repository?

Thanks! 😊

**Comment by arcan1s** [comment]
>   To me, it seems like it tries the clone the non-existing master branch instead pull_branch = main? So the question here is, am I doing something wrong or is this an actual bug?

well, first of all you have tried to use this trigger in the way I didn't expect to :smile: Somehow, technically it will work, but with issues. This trigger is supposed to use as master repository which contains packages inside it. However, there is a bug (to be precise missing logic) in which if you are using submodules, it will still lookup for master branch (that's actually the bug you are facing)

It is also an answer for your second question. Both remote pull and remote push triggers are supposed to work with single repository which contains multiple packages, e.g. you can check https://github.com/arcan1s/arcanisrepo, which is automatically generated by pull trigger and can be (with exception for ahriman-specific patches though!) used as source for push triggers

Let me check what can I do with keeping branches alive and add some workarounds for pulling single pkgbuilld repositories

**Comment by arcan1s** [comment]
> It is also an answer for your second question

let me clarify, it recursively looks inside cloned repository, finds each PKGBUILD there and register parent directory of the PKGBUILD  as source. That's why in your case, it treats your repos as valid

**Comment by arcan1s** [comment]
now it should work with the configuration above as expected, both found issues were fixed and available in [2.10.2](https://github.com/arcan1s/ahriman/releases/tag/2.10.2)

**Comment by dr460nf1r3** [comment]
This sounds really good! I just tested it, the specified repos however do not show up in the logs :eyes: This is on the latest commit of course. [Full logs here.](https://bin.garudalinux.org/?08f617565d26b4bb#8wWaDdQFe1QLJBeLwS6cizz3GNc2wxTn1AY62bHVWks4)

**Comment by arcan1s** [comment]
I checked your logs, looks like at some point I got some side effects, so I missed the case in which git is not initialized. The easiest workaround (looks like you are using container) is to create .gitconfig file in your mounted repository root with the following content:

```
[user]
  name = ahriman
  email = ahriman@localhost
```

(tip: file should be mounted inside container as `/var/lib/ahriman/.gitconfig`)

I'm working on fixing it, however, found some errors with processing _local_ packages (technically, using remote pull trigger will create them), so it might take some time

**Comment by dr460nf1r3** [comment]
I'll be happy to test anything you come up with! 😊

**Comment by arcan1s** [comment]
Changes have been merged into master, since you are using docker, you could just pull `arcan1s/ahriman:edge` image for your tests (from other major changes in comparison to the latest release there is also pkgrel bump, but I wouldn't except much issues with it at the moment)

**Comment by dr460nf1r3** [comment]
Just got to test it - it works just as expected now! :)
