### ISSUE TITLE
Create my own repository

### ISSUE THREAD

**Issue by Hayao0819** [arcan1s/ahriman#36]
I'm trying to use ahriman to build a small repository that hosts my original PKGBUILD.
I made the settings according to the documentation, but it is interrupted by # 34.
I don't know what to do to build my own repository and host it on GitHub.
I would like an example of an already built repository and detailed documentation on building a development environment.

**Comment by arcan1s** [comment]
> I'm trying to use ahriman to build a small repository that hosts my original PKGBUILD.

Just in case there is no ability to _build_ packages automatically which are not hosted in AUR (https://github.com/arcan1s/ahriman/issues/38)

>  I don't know what to do to build my own repository and host it on GitHub.

there is no option to sync it to github (yet) unfortunately. Only available options are either self-hosted server or S3. I will think about an ability to sync data to github https://github.com/arcan1s/ahriman/issues/37

>  I would like an example of an already built repository and detailed documentation on building a development environment.

Documentation (as well as gh-action which would be run automatically) still in progress. There is real-life example of the repository which at http://repo.arcanis.me/x86_64/index.html (hosted at S3) and there is status page here http://builds.arcanis.me/
