### ISSUE TITLE
How do I donate to this project

### ISSUE THREAD

**Issue by Hayao0819** [arcan1s/ahriman#39]
I hope this project makes it easy to manage repositories. But I can't write Python.
I'm sorry for the small amount, but I would like to donate in some way.

**Comment by arcan1s** [comment]
No, unfortunately you can't :) Personally I believe that "pet projects" (which ahriman is at the moment) should and can be developed only for fun, which makes any kind of payments incompatible with this idea.

Ideas, reports and (probably) some advertising is the best donation
