### ISSUE TITLE
Missing depend package

### ISSUE THREAD

**Issue by Hayao0819** [arcan1s/ahriman#44]
web subcommand require the package `aur/python-aiohttp-jinja2`

**Comment by arcan1s** [comment]
yea it does:

```
python-aiohttp-jinja2 (optional) – web server 
```

https://github.com/arcan1s/ahriman/blob/master/package/archlinux/PKGBUILD#L18
https://github.com/arcan1s/ahriman/blob/master/docs/faq.md#readme-mentions-web-interface-how-do-i-use-it

**Comment by Hayao0819** [comment]
Sorry, I missed it
