### ISSUE TITLE
Manage the list of packages and their sources

### ISSUE THREAD

**Issue by Hayao0819** [arcan1s/ahriman#46]
I intend to manage the repository in the long run.
Currently, I built a repository locally, but I want to manage the source AUR and PKGBUILD using Git.
Is there any way to do that?

I need to write a simple shell script to add and build PKGBUILD and packages managed in another repository to ahriman every time.

```bash
pkgs=("pkg1" "pkg2" ...)
for pkg in "${pkgs[@]}"; do
    sudo -u ahriman ahriman --unsafe -a x86_64 package-add --now "${pkg}"
done

**Comment by arcan1s** [comment]
yea currently for each local package you would need to run package-add command manually. Do you want to store your sources in git like AUR does?

**Comment by Hayao0819** [comment]
Yes, I hope to manage package list  by github

**Comment by arcan1s** [comment]
It should be supported now natively with #46

**Comment by Hayao0819** [comment]
Thanks for many updates. but there is no document about new features.

**Comment by arcan1s** [comment]
basically it is release log (I had practice with changelog, but would like to avoid to maintain manual list) which can be found here https://github.com/arcan1s/ahriman/releases
