### ISSUE TITLE
Store PKBUILDs in git repository

### ISSUE THREAD

**Issue by arcan1s** [arcan1s/ahriman#65]
## Feature summary

Idea is to store PKGBUILDs in local git repository which can be synced to any remote source.

### Cause of the feature request

Basically most of repositories provide github repositories with build files used for specific build. It might be useful to do the same, the possible reason to do that is to have reproducable builds and check instructions which were used for the build

**Comment by Hayao0819** [comment]
If you can build a package repository directly from PKGBUILD managed by any Git repository, it will be very easy.

Additionally, I would like automatic syncing (pull) with Git and updating of package binaries.

**Comment by arcan1s** [comment]
I'm thinking about extending triggers api, so it should be probably possible to fetch repo and check for updates there. I will take your case into account for development :)
