### ISSUE TITLE
How stable is the system on Docker?

### ISSUE THREAD

**Issue by Hayao0819** [arcan1s/ahriman#70]
I am currently running Ahriman on my own Arch Linux.
If it is stable enough to run on Docker, I will move it over to Synology's home server and have it running 24h.

Currently I have been adding PKGBUILDs manually with commands, but is it possible to add PKGBUILDs hosted in a specific repository on GitHub to ahriman and build them without any command line action from the web?

Also, is it possible to transfer the built repository to another remote using rsync or other methods?

**Comment by arcan1s** [comment]
> How stable is the system on Docker?

as for now docker image is considered as stable, most of features have been tested and work without any issues or restrictions. However, there are some limitations in "official" image which are not yet addressed:
* It requires separated instances for web and update process (like when it is run on real hardware), e.g. one `web` and one `repo-update`
* Build subcommands (including `web`) require `--privileged` flag, which is not really good for security (these permissions are required for mounting inside archlinux' `devtools`) (can be probably adjusted with capabilities, but haven't check it yet)
* Timer feature is not available in docker, which means that you will need to run _container_ periodically. However, this limitation is addressed in https://github.com/arcan1s/ahriman/commit/b97c8928e14f279700a4e7154d4406709cd31487 and should be available in `edge` image already as `daemon` subcommand (e.g. `docker run --privileged arcan1s/ahriman:edge daemon`

Also note about mounting and variables https://ahriman.readthedocs.io/en/latest/faq.html#docker-image

**Comment by arcan1s** [comment]
>  is it possible to add PKGBUILDs hosted in a specific repository on GitHub to ahriman and build them without any command line action from the web?

There is a https://github.com/arcan1s/ahriman/issues/65 (which, again, is not yet released, however available in edge image), which will allow you to fetch PKGBUILDs from your own repository, the configuration should be something like:

1. Create github/gitlab/gitea/whatever repository for pkgbuilds, e.g. https://github.com/arcan1s/pkgbuild
2. Clone repo, create subdirectory with pkgbuilds here, aim to have structure like this https://github.com/arcan1s/pkgbuild (it uses submodules, however, plain subdirectories should work either)
3. Configure triggers as following:

```ini
[build]
triggers = ahriman.core.report.ReportTrigger ahriman.core.upload.UploadTrigger ahriman.core.gitremote.RemotePullTrigger

[gitremote]
pull_url = https://github.com/arcan1s/pkgbuild.git
```

On each package update it will clone the specified repo and will use it as pkgbuild sources if possible. Note, however, that for packages listed in this repo, AUR checks will not work. Read also https://ahriman.readthedocs.io/en/latest/faq.html#err-i-have-remote-repository-with-pkgbuilds-and-would-like-to-get-versions-from-there-automatically

That's regarding syncing with git repo. For the second part of your question, I've added https://github.com/arcan1s/ahriman/commit/d98211e5e55e79e3dd62d2cb94df369b35eecc55 feature which will allow you to run full update from web just pressing "Update" button (disclaimer: not yet released, however available in edge image)

**Comment by arcan1s** [comment]
> Also, is it possible to transfer the built repository to another remote using rsync or other methods?

yea, sure. Firstly, you can use repo-backup/repo-restore subcommands https://ahriman.readthedocs.io/en/latest/faq.html#backup-and-restore. However it does not copy built packages.

If you would like to copy built packages also you can just rsync (kindly note that you would need to preserve file/directory owners). Instead of running subcommands, you rsync `/var/lib/ahriman` directory and its configurations (by default `/etc/ahriman.ini` and `/etc/ahriman.ini.d`). Note, that on _target_ system you still need to run `setup` subcommand in order to create devtools files

**Comment by Hayao0819** [comment]
Thank you for you repling. I meaned that I want to upload built packages with rsync.

I want to run rsync and transport built packages to another server when ahriman updates package.

**Comment by arcan1s** [comment]
> I want to run rsync and transport built packages to another server when ahriman updates package.

ah, I see. Then you need to follow instruction https://ahriman.readthedocs.io/en/latest/faq.html#wait-i-would-like-to-use-the-repository-from-another-server, configure like this:

```
[upload]
target = rsync

[rsync]
remote = 192.168.0.1:/srv/repo
```

prefix with user as usual if required, e.g. `remote = nobody@192.168.0.1:/srv/repo` and configure ssh keys for ahriman user (simply copy your `id_rsa` (or whatever is the name of your key) to `/var/lib/ahriman/.ssh/id_rsa` (with 600 or 400 permissions)

> Also, does the container support auto-start with system?

err, no it doesn't. Container is separated application which has to be run as usual if you would like to. E.g. you can write simple systemd service like

```
[Unit]
Description=ahriman docker service

[Service]
ExecStart=/usr/bin/docker run ...
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by Hayao0819** [comment]
I have read the documentation carefully and it says nothing about a means to modify the configuration files on Docker.
I think the method of logging into a Docker container and modifying it with Vi would work, but I don't think it is an elegant or appropriate way.

**Comment by arcan1s** [comment]
well, err, yea, it misses description. You can just do it as usual mount, e.g.
`docker run -v /local/path/to/overrides.ini:/etc/ahriman.ini.d/overrides.ini ...`

**Comment by Hayao0819** [comment]
Sorry, I'm stranger of Docker.
