### ISSUE TITLE
Cannot start web with Manjaro

### ISSUE THREAD

**Issue by Hayao0819** [arcan1s/ahriman#98]
## Summary

Cannot start ahriman-web

### Steps to reproduce

1. Install ahriman 2.9.0 on manjaro
2. Install all optdepends
3. Set up following document
4. Show status of `ahriman-web@x86_64.service`

### Expected behavior

Run without error

### Logs

<img width="1168" alt="image" src="https://github.com/arcan1s/ahriman/assets/32128205/63779628-4e23-4f9f-ace6-66f2e56ea432">

<img width="1236" alt="image" src="https://github.com/arcan1s/ahriman/assets/32128205/6fd6c94d-5ae4-4e0b-b4af-d442407021e8">

<img width="529" alt="image" src="https://github.com/arcan1s/ahriman/assets/32128205/efe47b4e-97a0-4d50-b642-49fb3985188e">

**Comment by arcan1s** [comment]
aiohttp-apispec has version 2.x, but 3+ is required

```
yay -S python-aiohttp-apispec>=3.0.0
```

(or whichever helper you are using)

Currently there is only [python-aiohttp-apispec-git](https://aur.archlinux.org/packages/python-aiohttp-apispec-git) package which provides these features

**Comment by Hayao0819** [comment]
Is there a option to rebuild all package whose build has been failed?

**Comment by arcan1s** [comment]
not really

1. From web interface you can sort by status (or even use search by `failed`), check all, run update function
2. From console you can use something like `sudo -u ahriman ahriman package-add --now $(ahriman -a x86_64 package-status -s failed | grep -v '^\s')`

**Comment by Hayao0819** [comment]
Hmm... Is there a way to rebuild without any dependancy to fix build error?

**Comment by arcan1s** [comment]
`package-add --no-dependencies --now`?

**Comment by arcan1s** [comment]
closing the case due to inactivity
